version: '3'

services:
  tp_final:
    build: ../tpFinal
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://docker_app_bazar:3306/app_bazar?createDatabaseIfNotExist&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: root
    restart: always
    depends_on:
      docker_app_bazar:
        condition: service_healthy
  docker_app_bazar:
    image: mysql:8.0.28
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: app_bazar
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10